Repository matteokeole/fedexpress, pull requests merged in 2024-06, with the labels that each got.

#1 OrderStatus enum
  controllers/beerOrderController.js
  controllers/orderController.js
  models/Order.js
  models/index.js
Labels: enhancement

#2 add route bar
  controllers/barController.js
Labels: enhancement

#3 Feat api beer
  controllers/beerController.js
  routers/beerRouter.js
Labels: enhancement

#4 Order API
  controllers/orderController.js
  forms/order/createOrderForm.js
  forms/order/updateOrderForm.js
  routers/orderRouter.js
Labels: enhancement

#5 add form to api bar
  controllers/barController.js
  forms/bar/createBarForm.js
  forms/bar/updateBarForm.js
  routers/barRouter.js
Labels: enhancement

#7 Connect Bar to Order API
  controllers/orderController.js
  forms/order/createOrderForm.js
  forms/order/updateOrderForm.js
  routers/beerOrderRouter.js
Labels: bug, enhancement

#6 Feat connect bar to beer
  controllers/beerController.js
  forms/beer/createBeerForm.js
  forms/beer/updateBeerForm.js
  routers/beerRouter.js
Labels: enhancement

#8 Bar average degree API route
  controllers/barController.js
  controllers/beerOrderController.js
  routers/barRouter.js
  routers/beerOrderRouter.js
Labels: enhancement

#10 add barByName and barByCity
  controllers/barController.js
  controllers/beerOrderController.js
Labels: enhancement

#9 Beer order API
  controllers/beerOrderController.js
  models/Beer.js
  models/BeerOrder.js
  models/Order.js
  routers/beerOrderRouter.js
Labels: enhancement

#12 Style
  controllers/barController.js
  controllers/beerController.js
  controllers/beerOrderController.js
  controllers/orderController.js
  models/Bar.js
  models/Beer.js
  models/Order.js
  models/index.js
  routers/beerRouter.js
  routers/orderRouter.js
Labels: invalid
